export const LOAD_CATEGORY_START = 'LOAD_CATEGORY_START';

export const LOAD_GENERIC_FILTER_START = 'LOAD_GENERIC_FILTER_START';

export const LOAD_REPORT_FILTER_START = 'LOAD_REPORT_FILTER_START';

export const LOAD_CHART_FILTER_START = 'LOAD_CHART_FILTER_START';

export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';

export const SELECT_DATE = 'SELECT_DATE';

export const LOAD_GENERIC_FILTER_SUCCESS = 'LOAD_GENERIC_FILTER_SUCCESS';

export const LOAD_CHART_FILTER_SUCCESS = 'LOAD_CHART_FILTER_SUCCESS';

export const LOAD_REPORT_FILTER_SUCCESS = 'LOAD_REPORT_FILTER_SUCCESS';

export const CHANGE_CHART_TYPE = 'CHANGE_CHART_TYPE';

export const LOAD_MAP = 'LOAD_MAP';
